name: deploy development
on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build project
        run: mvn clean package

      - name: Get project version
        id: version
        run: echo "value=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)" >> "$GITHUB_OUTPUT"

      - name: Upload jar
        uses: actions/upload-artifact@v7
        with:
          retention-days: 5
          name: minecraft-server-manager-backend-${{ steps.version.outputs.value }}
          path: target/minecraft-server-manager-backend-${{ steps.version.outputs.value }}.jar
  deploy:
    needs: build-and-upload
    runs-on: [self-hosted, Windows]
    environment: development
    steps:
      - name: Download jar
        uses: actions/download-artifact@v7
        with:
          name: minecraft-server-manager-backend-${{ needs.build-and-upload.outputs.version }}